config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks do
    collection do
      get 'slow'
    end
    collection do
      get 'fast'
    end
    collection do
      get 'high'
    end
    collection do
      get 'low'
    end
  end
  resources :categories, only: :show
  resources :priorities, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :priority

  validates :start_time, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :category_id, presence: true
  validates :priority_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action:get_category
  before_action:get_priority

  def get_category
    @categories = Category.all
  end

  def get_priority
    @priorities = Priority.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @tasks = Task.where(category_id: params[:id])
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  def show
    @priority = Priority.find(params[:id])
    @tasks = Task.where(category_id: params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.includes(:category, :priority)
   
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  def slow
    @tasks = Task.all.order("start_time DESC").includes(:category, :priority)
  end

  def high
    @tasks = Task.all.order("priority_id DESC").includes(:category, :priority)
  end

  def low
    @tasks = Task.all.order("priority_id ASC").includes(:category, :priority)
  end

  def fast
    @tasks = Task.all.order("start_time ASC").includes(:category, :priority)
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :start_time, :category_id, :priority_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
  def show
    @priority = Priority.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/show.html.erb
<div class="tasks__list">
  <% @category.tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "タスク一覧", tasks_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "新規投稿", new_task_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">カテゴリ<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @categories.each do |category| %>
                  <li><%= link_to category.name, category_path(category) %></li>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">優先度<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @priorities.each do |priority| %>
                  <li><%= link_to priority.name, priority_path(priority) %></li>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">並び替え<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "優先度高い", high_tasks_path %></li>
                <li><%= link_to "優先度低い", low_tasks_path %></li>
                <li><%= link_to "納期早い", fast_tasks_path %></li>
                <li><%= link_to "納期遅い", slow_tasks_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="contena">
      <%= yield %>
    </div>



  </body>
</html>

app/views/priorities/show.html.erb
<div class="tasks__list">
  <% @priority.tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_task.html.erb
<div class="panel-heading">
  <div class="content__top">
    <h4><%= task.title %></h4>
    <p><%= task.priority.name %></p>
  </div>
  <h5><%= task.category.name %></h5>
</div>
<table class="table">
  <div class="content__bottom">
    <h4><%= task.content %></h4>
    <h6><%= "#{task.start_time.strftime("%Y/%m/%d")}まで" %></h6>
  </div>
</table>

app/views/tasks/edit.html.erb
<div class="form">
  <div class="form__contena">
    <%= form_with(model: @task, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :start_time, "納期" %><br>
        <%= form.date_select :start_time, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <div class="form-group">
        <%= form.label :title, "タイトル" %><br>
        <%= form.text_field :title, class: "form-control", id: "formGroupExampleInput", placeholder:"未入力" %>
      </div>
      <div class="form-group">
        <%= form.label :content, "内容" %><br>
        <%= form.text_area :content, class: "form-control", id: "formGroupExampleInput", placeholder:"未入力" %>
      </div>
      <div class="form-group">
        <%= form.label :category_id, "カテゴリ" %><br>
        <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, {prompt:"選択してください"}, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <div class="form-group">
        <%= form.label :priority_id, "優先度" %><br>
        <%= form.select :priority_id, @priorities.map{ |priority| [priority.name, priority.id] }, {prompt:"選択してください"}, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <button type="submit" class="btn btn-default">保存</button>
    </div>
  </div>
<% end %>

app/views/tasks/fast.html.erb
<div class="tasks__list">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/high.html.erb
<div class="tasks__list">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date.day %>

  <% tasks.each do |task| %>
    <div>
      <%= link_to task.title, task %>
    </div>
  <% end %>
<% end %>

<div class="tasks__list">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/low.html.erb
<div class="tasks__list">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="form">
  <div class="form__contena">
    <%= form_with(model: @task, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :start_time, "納期" %><br>
        <%= form.date_select :start_time, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <div class="form-group">
        <%= form.label :title, "タイトル" %><br>
        <%= form.text_field :title, class: "form-control", id: "formGroupExampleInput", placeholder:"未入力" %>
      </div>
      <div class="form-group">
        <%= form.label :content, "内容" %><br>
        <%= form.text_area :content, class: "form-control", id: "formGroupExampleInput", placeholder:"未入力" %>
      </div>
      <div class="form-group">
        <%= form.label :category_id, "カテゴリ" %><br>
        <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, {prompt:"選択してください"}, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <div class="form-group">
        <%= form.label :priority_id, "優先度" %><br>
        <%= form.select :priority_id, @priorities.map{ |priority| [priority.name, priority.id] }, {prompt:"選択してください"}, class: "form-control", id: "formGroupExampleInput" %>
      </div>
      <button type="submit" class="btn btn-default">保存</button>
    </div>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class=show>
  <div class="show__contena">
    <h2 class="show__contena--title">見出し</h2>
    <h4><%= @task.title %></h4>
    <h2 class="show__contena--title">内容</h2>
    <h4><%= @task.content %></h4>
    <h2 class="show__contena--title">カテゴリ</h2>
    <h4><%= @task.category.name %></h4>
    <h2 class="show__contena--title">納期</h2>
    <h4><%= "#{@task.start_time.strftime("%Y/%m/%d")}まで" %></h4>
    <h2 class="show__contena--title">優先度</h2>
    <h4><%= @task.priority.name %></h4>
  </div>
  <div class="show__item">
    <%= link_to(content_tag(:i, '', class: 'fas fa-edit fa-2x'), edit_task_path(@task)) %>
    <%= link_to task_path(@task), :method => :delete, data: { confirm: 'タスク完了ですか？' } do %>
      <i class="far fa-trash-alt fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/tasks/slow.html.erb
<div class="tasks__list">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <% if task.priority.id == 1 %>
        <div class="panel panel-success">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 2 %>
        <div class="panel panel-primary">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% elsif task.priority.id == 3 %>
        <div class="panel panel-info">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>  
      <% elsif task.priority.id == 4 %>
        <div class="panel panel-warning">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>   
      <% elsif task.priority.id == 5 %>
        <div class="panel panel-default">
          <%= render partial: "tasks/task", locals: { task: task } %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>